import React, { useState } from 'react';
import { Download, FileText, ChevronRight, Printer } from 'lucide-react';
import { getPredictedPapers, PaperSet } from '../utils/predictedPapersData';
import { QuestionPaperTemplate } from './QuestionPaperTemplate';

/**
 * MockTestDashboard
 * A high-end dashboard to manage and download PLUS2AI official prediction papers.
 */
export const MockTestDashboard: React.FC<{ onBack: () => void }> = ({ onBack }) => {
    const [papers] = useState<PaperSet[]>(getPredictedPapers());
    const [selectedPaper, setSelectedPaper] = useState<PaperSet | null>(null);

    const handleDownload = (paper: PaperSet) => {
        setSelectedPaper(paper);
        // Delay significantly to ensure LaTeX/Math formulas are fully rendered, then trigger print
        setTimeout(() => {
            window.print();
            setSelectedPaper(null); 
        }, 1500);
    };

    return (
        <div className="min-h-screen bg-slate-50 p-6 md:p-12">
            {/* If a paper is selected for printing, render ONLY the paper */}
            {selectedPaper && (
                <div className="fixed inset-0 z-[100] bg-white overflow-auto print:static print:h-auto print:overflow-visible print-section">
                    <QuestionPaperTemplate
                        title={selectedPaper.title}
                        subject={selectedPaper.subject}
                        questions={selectedPaper.questions}
                        setName={selectedPaper.setName}
                    />
                    <button 
                        onClick={() => setSelectedPaper(null)}
                        className="no-print fixed top-4 right-4 bg-slate-800 text-white px-4 py-2 rounded-lg shadow-lg hover:bg-slate-700 transition-all flex items-center gap-2"
                    >
                        <ChevronRight className="rotate-180" size={18} /> Close Preview
                    </button>
                </div>
            )}

            <div className={`max-w-5xl mx-auto transition-opacity duration-300 ${selectedPaper ? 'opacity-0 pointer-events-none' : 'opacity-100'}`}>
                <header className="mb-12">
                    <button 
                        onClick={onBack}
                        className="mb-8 text-slate-500 hover:text-slate-800 transition-colors flex items-center gap-1 font-medium"
                    >
                        <ChevronRight className="rotate-180" size={18} /> Back to Dashboard
                    </button>
                    <div className="flex flex-col md:flex-row md:items-end justify-between gap-6">
                        <div>
                            <h1 className="font-black tracking-tight font-outfit text-xl leading-none uppercase italic">
                                <span style={{ color: '#0a1a16' }}>plus2</span>
                                <span style={{ color: '#ff7f50' }}>AI</span>
                            </h1>
                            <p className="text-slate-600 text-lg max-w-2xl">
                                Access and download high-fidelity KCET 2026 AI mocktest papers generated by the <span style={{ color: '#0a1a16' }}>plus2</span><span style={{ color: '#ff7f50' }}>AI</span> REI v17 engine.
                            </p>
                        </div>
                        <div className="bg-white px-4 py-2 rounded-full border border-slate-200 text-sm font-semibold text-slate-500 flex items-center gap-2 shadow-sm">
                            <span className="w-2 h-2 bg-green-500 rounded-full animate-pulse" />
                            REI v17 Calibrated
                        </div>
                    </div>
                </header>

                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                    {papers.map((paper) => (
                        <div 
                            key={paper.id}
                            className="bg-white rounded-2xl border border-slate-200 p-6 shadow-sm hover:shadow-xl hover:-translate-y-1 transition-all group overflow-hidden relative"
                        >
                            {/* Accent Bar */}
                            <div className={`absolute top-0 left-0 right-0 h-1.5 ${
                                paper.subject === 'Physics' ? 'bg-blue-500' : 
                                paper.subject === 'Mathematics' ? 'bg-indigo-600' :
                                paper.subject === 'Chemistry' ? 'bg-emerald-500' :
                                paper.subject === 'Biology' ? 'bg-rose-500' : 'bg-coral-500'
                            }`} />

                            <div className="flex justify-between items-start mb-6">
                                <div className="p-3 bg-slate-50 rounded-xl group-hover:bg-slate-100 transition-colors">
                                    <FileText className="text-slate-700" size={24} />
                                </div>
                                <span className="bg-slate-100 text-slate-600 px-3 py-1 rounded-full text-xs font-bold tracking-widest uppercase">
                                    SET {paper.setName}
                                </span>
                            </div>

                            <h3 className="text-xl font-bold text-slate-900 mb-2 truncate">
                                {paper.subject} Prediction
                            </h3>
                            <p className="text-slate-500 text-sm mb-8">
                                60 Questions • 80 Minutes • KCET 2026 Layout
                            </p>

                            <button 
                                onClick={() => handleDownload(paper)}
                                className="w-full bg-slate-900 text-white py-3 rounded-xl font-bold flex items-center justify-center gap-2 hover:bg-slate-800 transition-all shadow-md active:scale-[0.98]"
                            >
                                <Printer size={18} /> Print to PDF
                            </button>
                        </div>
                    ))}
                </div>

                <footer className="mt-20 pt-8 border-t border-slate-200 text-center">
                    <p className="text-slate-400 text-sm mb-4">
                        &copy; 2026 Plus2AI Teacher Studio. All papers are proprietary prediction models.
                    </p>
                    <div className="flex justify-center gap-4">
                         {/* Placeholder for legal/help links if needed */}
                    </div>
                </footer>
            </div>
            
        </div>
    );
};
