import React from 'react';
import './PaperWatermark.css';
import RichMarkdownRenderer from './RichMarkdownRenderer';

interface Question {
    id: string;
    text: string;
    options: string[];
    marks?: number;
    topic?: string;
}

interface PaperProps {
    title: string;
    subject: string;
    questions: Question[];
    setName: string;
    timeInMinutes?: number;
    maxMarks?: number;
}

/**
 * QuestionPaperTemplate
 * Renders a professional KCET-style question paper.
 * Designed for high-fidelity print output.
 */
export const QuestionPaperTemplate: React.FC<PaperProps> = ({
    title,
    subject,
    questions,
    setName,
    timeInMinutes = 80,
    maxMarks = 60
}) => {
    return (
        <div className="paper-container">
            {/* Header Section */}
            <header className="paper-header">
                <div className="paper-brand">
                    <div className="brand-text">Plus2<span>AI</span> mock test</div>
                    <div className="set-indicator">SET - {setName}</div>
                </div>

                <div className="exam-meta">
                    <div className="meta-left">
                        <div className="meta-item">Subject: <strong>{subject.toUpperCase()}</strong></div>
                        <div className="meta-item">Duration: <strong>{timeInMinutes} Minutes</strong></div>
                    </div>
                    <div className="meta-right">
                        <div className="meta-item">Version Code: <strong>REI-v17</strong></div>
                        <div className="meta-item">Max Marks: <strong>{maxMarks}</strong></div>
                    </div>
                </div>

                <div className="reg-no-section" style={{ marginTop: '1rem' }}>
                    <div className="option" style={{ alignItems: 'center' }}>
                        <span>Register Number:</span>
                        <div className="reg-no-box">
                            {[...Array(8)].map((_, i) => (
                                <div key={i} className="box" />
                            ))}
                        </div>
                    </div>
                </div>
            </header>

            {/* Official Instructions */}
            <section className="paper-instructions">
                <h3>Instructions to Candidates</h3>
                <ol>
                    <li>Each question carries <strong>1 mark</strong>. There is <strong>no negative marking</strong>.</li>
                    <li>Verify that this question paper contains <strong>60 questions</strong>.</li>
                    <li>Mark your answers correctly on the OMR sheet provided.</li>
                    <li>This paper is a proprietary prediction model generated by <strong>Plus2AI DNA (REI v17)</strong>.</li>
                    <li>Usage of scientific calculators is prohibited.</li>
                    <li><strong>DISCLAIMER:</strong> This AI-generated prediction is intended for practice ONLY. Plus2AI assumes no legal liability for any discrepancies with actual exam content or outcomes.</li>
                </ol>
            </section>

            {/* Questions Section */}
            <main className="questions-grid">
                {questions.map((q, index) => (
                    <div key={q.id} className="question-item">
                        <div className="question-text">
                            <strong>{index + 1}.</strong> <RichMarkdownRenderer text={q.text} className="inline" />
                        </div>
                        <div className="options-grid">
                            {q.options.map((opt, optIdx) => (
                                <div key={optIdx} className="option">
                                    <span className="option-letter">({String.fromCharCode(65 + optIdx)})</span>
                                    <span className="option-content">
                                        <RichMarkdownRenderer text={opt} className="inline" />
                                    </span>
                                </div>
                            ))}
                        </div>
                    </div>
                ))}
            </main>

            {/* Footer / Pagination Placeholder */}
            <footer className="paper-footer">
                <div className="footer-disclaimer" style={{ fontSize: '7pt', opacity: 0.8, maxWidth: '60%' }}>
                    Disclaimer: AI prediction for practice only. Plus2AI is not legally liable for results/discrepancies.
                </div>
                <div>&copy; 2026 Plus2AI</div>
                <div className="page-number">KCET 2026 AI mocktest | Page&nbsp;</div>
            </footer>
        </div>
    );
};
