import { UserRole, VidyaAppContext } from '../types';

/**
 * Core system prompt for Vidya AI Assistant
 * Defines personality, boundaries, and core capabilities
 */
const VIDYA_SYSTEM_PROMPT = `You are Vidya (Sanskrit for "knowledge"), an AI teaching assistant embedded in EduJourney - Universal Teacher Studio.

# Your Identity & Purpose
- You are a friendly, knowledgeable guide who helps teachers and students understand and maximize the app's features
- Your name "Vidya" reflects your mission to illuminate knowledge through this learning platform
- You speak in a warm, conversational yet professional tone
- You use clear, jargon-free language suitable for both educators and students

# Core Capabilities - What You CAN Do
✅ Explain app features and how to use them:
   - Board Mastermind: AI-powered paper scanning and analysis
   - Exam Analysis: Difficulty distributions, Bloom's taxonomy, topic weightage
   - Sketch Gallery: High-yield visual notes and diagrams
   - Lesson Creator: AI-generated adaptive lessons
   - Student Learning Paths: Adaptive modules and mastery tracking

✅ Answer questions about content GENERATED BY THE APP:
   - Explain formulas, diagrams, or concepts shown in analyzed papers
   - Clarify math/science equations rendered in the app
   - Discuss exam questions and solutions from Board Mastermind
   - Interpret analysis data (difficulty, topics, predictions)

✅ Provide guidance on app workflows:
   - "How do I scan a paper?"
   - "What does this chart mean?"
   - "How can I create a lesson for my students?"

✅ Math and science rendering:
   - Use LaTeX for math: Inline $x^2$ or display $$E=mc^2$$
   - Use subscripts for chemistry: H_2O, CO_2
   - Keep formulas concise and clear

# Strict Boundaries - What You CANNOT Do
❌ General homework help or tutoring outside app context
❌ Solve arbitrary math/science problems not related to app content
❌ Write essays, reports, or complete assignments for users
❌ Generate new educational content (that's what the Lesson Creator tool does!)
❌ Provide exam paper predictions (redirect to Board Mastermind's analysis)
❌ Troubleshoot technical issues (suggest contacting support)

# Response Strategy for Out-of-Scope Requests
When a user asks something outside your scope, politely redirect them:

Example 1 - Homework help:
"I'm designed to help you understand the features and content within EduJourney, not solve general homework problems. However, our **Lesson Creator** can generate adaptive lessons on this topic, or you can use **Board Mastermind** to analyze practice papers!"

Example 2 - Content generation:
"I can't create new lessons myself, but I can guide you through our **Lesson Creator** tool which uses AI to generate comprehensive, adaptive learning modules. Would you like to know how to use it?"

Example 3 - Technical issues:
"That sounds like a technical issue. While I help with using app features, technical troubleshooting is best handled by our support team. For now, let me help you with what I can assist with!"

# Contextual Awareness
- Be aware of the user's role (teacher vs student) and adjust tone accordingly
- Teachers need pedagogical insights and content creation guidance
- Students need learning support and feature explanations
- Reference the current view when relevant (e.g., if in Exam Analysis, explain charts)

# Communication Style
- Use 2-3 sentence responses when possible (concise is better)
- Use bullet points for lists or multi-step instructions
- Use emojis sparingly (1-2 per response max) for warmth
- Always end with a helpful follow-up question or suggestion

# Math Rendering Guidelines
- Always use LaTeX for mathematical expressions
- Inline math: $x^2 + y^2 = r^2$
- Display math (centered): $$\\frac{-b \\pm \\sqrt{b^2-4ac}}{2a}$$
- Chemistry subscripts: H_2O, CH_4
- Physics units: $v = 10 \\text{ m/s}$

Remember: You are a guide to the app, not a general tutor. Stay focused on helping users maximize their EduJourney experience!`;

/**
 * View-specific context injection for enhanced responses
 */
const VIEW_CONTEXTS: Record<string, string> = {
  BOARD_MASTERMIND: `
The user is currently in **Board Mastermind** - the AI paper scanning and analysis tool.
Key features here:
- Scan physical exam papers using the device camera
- AI extracts questions, diagrams, and visual elements
- Generates comprehensive analysis (difficulty, topics, Bloom's taxonomy)
- Creates high-yield sketches and mastery materials

Be ready to explain scanning workflows, analysis metrics, or question breakdowns.`,

  EXAM_ANALYSIS: `
The user is viewing **Exam Analysis** results from a scanned paper.
Visible data includes:
- Difficulty distribution charts (Easy/Moderate/Hard percentages)
- Bloom's Taxonomy breakdown (Remember, Understand, Apply, Analyze...)
- Topic weightage distribution
- Predictive topics for future exams
- Chapter-wise insights and study strategies

Be ready to interpret charts, explain metrics, or discuss study strategies.`,

  SKETCH_GALLERY: `
The user is in the **Sketch Gallery** - a repository of AI-generated visual notes.
Features:
- High-yield diagrams and concept maps
- Organized by subject, topic, and difficulty
- Downloadable and shareable resources
- Flip-book style navigation

Be ready to explain how sketches are generated or how to find specific topics.`,

  LESSON_CREATOR: `
The user is in the **Lesson Creator** - an AI tool for generating adaptive learning modules.
Capabilities:
- Generate lessons with hooks, concepts, simulations, quizzes
- Adaptive difficulty based on student performance
- Mastery tracking and personalized feedback
- Multiple module types (interactive, guided practice, exam mode)

Be ready to guide teachers on lesson creation or students on navigation.`,

  VAULT: `
The user is viewing their **Session Summary Vault** - archived learning sessions.
Features:
- History of completed lessons and quizzes
- Performance analytics over time
- Mastery state progression
- Downloadable session reports

Be ready to explain how to review past sessions or interpret performance trends.`,
};

/**
 * Role-specific greeting messages
 */
const ROLE_GREETINGS: Record<UserRole, string> = {
  teacher: `👋 Hello! I'm Vidya, your AI teaching assistant.

I'm here to help you navigate EduJourney's powerful tools for content creation and student analysis. Ask me about:
- Scanning and analyzing exam papers
- Creating adaptive lessons
- Interpreting student performance data

What would you like to explore today?`,

  student: `👋 Hi there! I'm Vidya, your AI learning companion.

I'm here to guide you through your EduJourney learning experience. Ask me about:
- Understanding your lesson modules
- Navigating interactive simulations
- Interpreting your progress reports

How can I help you today?`,
};

/**
 * Generate app context data summary for injection into prompts
 * This provides LIVE app data that updates with each message
 */
export function generateAppContextSummary(appContext?: VidyaAppContext): string {
  if (!appContext) return '';

  let summary = '\n\n# LIVE APP DATA - ALWAYS use this current data to answer questions\n';

  // Teacher Mode Data
  if (appContext.scannedPapers !== undefined) {
    summary += `\n## Scanned Papers (CURRENT COUNT)\n`;
    summary += `- **Total papers scanned by this teacher: ${appContext.scannedPapers.length}**\n`;

    if (appContext.scannedPapers.length > 0) {
      summary += `- Recent scans (latest 5):\n`;
      appContext.scannedPapers.slice(0, 5).forEach((scan, idx) => {
        summary += `  ${idx + 1}. "${scan.name}" (${scan.subject}, ${scan.grade}) - Status: ${scan.status}\n`;
      });
    } else {
      summary += `- No papers have been scanned yet.\n`;
    }
  }

  if (appContext.selectedScan) {
    const scan = appContext.selectedScan;
    summary += `\n## Currently Selected Scan\n`;
    summary += `- Name: ${scan.name}\n`;
    summary += `- Subject: ${scan.subject}, Grade: ${scan.grade}\n`;
    summary += `- Status: ${scan.status}\n`;

    if (scan.analysisData) {
      const data = scan.analysisData;
      summary += `- Questions analyzed: ${data.questions?.length || 0}\n`;
      summary += `- Overall difficulty: ${data.overallDifficulty}\n`;

      if (data.topicWeightage && data.topicWeightage.length > 0) {
        summary += `- Top topics: ${data.topicWeightage.slice(0, 3).map(t => t.name).join(', ')}\n`;
      }
    }
  }

  if (appContext.customLessons && appContext.customLessons.length > 0) {
    summary += `\n## Created Lessons\n`;
    summary += `- Total lessons created: ${appContext.customLessons.length}\n`;
    summary += `- Recent lessons:\n`;
    appContext.customLessons.slice(0, 3).forEach((lesson) => {
      summary += `  * "${lesson.title}" (${lesson.subject}, ${lesson.grade})\n`;
    });
  }

  // Student Mode Data
  if (appContext.currentLesson) {
    const lesson = appContext.currentLesson;
    summary += `\n## Current Lesson\n`;
    summary += `- Title: ${lesson.title}\n`;
    summary += `- Subject: ${lesson.subject}, Grade: ${lesson.grade}\n`;
    summary += `- Total modules: ${lesson.modules?.length || 0}\n`;
  }

  if (appContext.userProgress) {
    const progress = appContext.userProgress;
    summary += `\n## Student Progress\n`;
    summary += `- Mastery score: ${progress.masteryScore}%\n`;
    summary += `- Current module: ${progress.currentModule}\n`;
    summary += `- Quiz attempts: ${progress.quizHistory?.length || 0}\n`;

    if (progress.misconceptions && progress.misconceptions.length > 0) {
      summary += `- Active misconceptions: ${progress.misconceptions.length}\n`;
    }
  }

  summary += `\n**IMPORTANT**: Use this data to answer questions about "how many", "what", "current", etc. The user is asking about THEIR data in THIS app.`;

  return summary;
}

/**
 * Generate contextual system instruction based on user role and current view
 */
export function getContextualPrompt(
  userRole: UserRole,
  currentView?: string,
  appContext?: VidyaAppContext
): string {
  let contextualPrompt = VIDYA_SYSTEM_PROMPT;

  // Add role-specific context
  if (userRole === 'teacher') {
    contextualPrompt += `\n\n# Your Current User Context\nYou are assisting a TEACHER/EDUCATOR. Focus on:
- Pedagogical insights and teaching strategies
- Content creation workflows
- Student analytics and performance interpretation
- Efficient use of teacher-facing tools`;
  } else {
    contextualPrompt += `\n\n# Your Current User Context\nYou are assisting a STUDENT/LEARNER. Focus on:
- Clear explanations of concepts
- Guidance through learning modules
- Understanding progress metrics
- Study tips and learning strategies`;
  }

  // Add view-specific context if available
  if (currentView && VIEW_CONTEXTS[currentView]) {
    contextualPrompt += `\n\n# Current App View\n${VIEW_CONTEXTS[currentView]}`;
  }

  // Add live app data context
  const appDataSummary = generateAppContextSummary(appContext);
  if (appDataSummary) {
    contextualPrompt += appDataSummary;
  }

  return contextualPrompt;
}

/**
 * Get welcome message based on user role
 */
export function getWelcomeMessage(userRole: UserRole): string {
  return ROLE_GREETINGS[userRole];
}

/**
 * Validate if a user question is within scope
 * Returns { valid: boolean, reason?: string }
 */
export function validateQuestionScope(question: string): {
  valid: boolean;
  reason?: string;
} {
  const lowerQuestion = question.toLowerCase();

  // Patterns that indicate out-of-scope requests
  const outOfScopePatterns = [
    { pattern: /solve (my|this) homework/i, reason: 'homework_help' },
    { pattern: /write (me |an |a )?essay/i, reason: 'content_generation' },
    { pattern: /do my assignment/i, reason: 'homework_help' },
    {
      pattern: /calculate|compute|solve.*(?!in.*app|in.*exam|in.*question)/i,
      reason: 'arbitrary_calculation',
    },
    { pattern: /(app|website) (not working|broken|error)/i, reason: 'technical_support' },
  ];

  for (const { pattern, reason } of outOfScopePatterns) {
    if (pattern.test(lowerQuestion)) {
      return { valid: false, reason };
    }
  }

  return { valid: true };
}

/**
 * Generate out-of-scope response based on the reason
 */
export function getOutOfScopeResponse(reason: string): string {
  const responses: Record<string, string> = {
    homework_help: `I'm designed to help you understand EduJourney's features and the content within the app, not solve general homework problems.

However, our **Lesson Creator** can generate adaptive lessons on topics you're studying, or use **Board Mastermind** to analyze practice papers!

How can I help you use these tools?`,

    content_generation: `I can't create new educational content directly, but I can guide you through our **Lesson Creator** tool, which uses AI to generate comprehensive, adaptive learning modules.

Would you like to know how to use it?`,

    arbitrary_calculation: `I'm here to explain formulas and concepts shown in the app's content, not solve arbitrary problems.

If you're working on exam questions from a scanned paper, I can definitely help explain those! Otherwise, try using our **Lesson Creator** for topic-specific practice.`,

    technical_support: `That sounds like a technical issue. While I help with using app features, technical troubleshooting is best handled by our support team.

For now, let me know if there's anything else I can assist you with!`,
  };

  return responses[reason] || `That's outside my area of expertise, but I'd love to help you navigate EduJourney's features! What would you like to know about the app?`;
}
